apiVersion: apps/v1
kind: Deployment
metadata:
  name: cado-poc-cluster
  namespace: cado-poc-cluster
  labels:
    app: cado-poc-cluster-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cado-poc-cluster-app
  template:
    metadata:
      labels:
        app: cado-poc-cluster-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.21
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
